apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: telehealth  
spec:
  replicas: 2  # Start with 2 replicas
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  # Zero downtime updates
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: itsankit123/telemedicine-frontend:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "512Mi"
            cpu: "300m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        envFrom:
        - configMapRef:
            name: frontend-config
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5